export {default as BlogPage} from './BlogPage'
export {default as LoginPage} from './LoginPage'
export {default as Page404} from './Page404'
export {default as ProductsListingPage} from './ProductsListingPage'
export {default as UserPage} from './UserPage'
export {default as DashboardAppPage} from './DashboardAppPage'
export {default as MailPage} from './MailPage'
export {default as ProductDetailPage} from './ProductDetailPage'